# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  employeeonboardingsystem-app:
    image: employeeonboardingsystem
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://employeeonboardingsystem-postgresql:5432/employeeonboardingsystem
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://employeeonboardingsystem-postgresql:5432/employeeonboardingsystem
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - '8080:8080'
  employeeonboardingsystem-postgresql:
    image: postgres:13.4
    # volumes:
    #   - ~/volumes/jhipster/employeeonboardingsystem/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=employeeonboardingsystem
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - '5432:5432'
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION="JKU"
      - LDAP_DOMAIN=jku.at
    ports:
      - '389:389'

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - '6443:443'
    depends_on:
      - openldap
